### ISSUE TITLE
How to realise visualization in evaluator files

### ISSUE THREAD

**Issue by Cxx0822** [vita-epfl/s-attack#2]
Hello, your article on pedestrian prediction has inspired me a lot. After debugging the code, I want to find out how to visualize the final result, because only a few data can be seen in the debugging process, and I don't know the implementation process. If you like, can you explain to me in detail how to do the visualization part？

**Comment by SaeedSaadatnejad** [comment]
Hello,
Thank you for your interest in our project.

There is a config named “show_limit”, which you can control in the run.sh file and it indicates how many examples will be plotted (by default it is 50).
The functions for drawings are named draw_two_tensor and draw_one_tensor which are used in the trajnetbaselines/lstm/run.py and trajnetbaselines/sgan/run.py files. We only plot some parts of the data that you can modify according to your needs.
This part will be updated soon for a more user-friendly api.

Please let us know in case of any ambiguities.
