### ISSUE TITLE
PECNet and STG-CNN

### ISSUE THREAD

**Issue by ericaweng** [vita-epfl/s-attack#3]
Dear authors,

I've noticed there is no option in your code to test S-Attack on PECNet and STG-CNN, two methods for which you provide adversarial attack results in your paper. I was wondering if you were planning on making your code for these two available, or if there's some way to install the dependencies separately ourselves.

Thank you,
Erica

**Comment by SaeedSaadatnejad** [comment]
Dear Erica,

We are now busy with a close deadline. After that, we will consider if we can publish other parts in the same format.
Generally, we provided a plug-and-play module for attacking any victim model. So in case you want to attack some arbitrary models, you should load their codes and models, freeze them and then the attack function is required to find those perturbations. Please take a look at the run.py files and how the attack and attack_batch functions were defined. Hope this information is helpful.

Best regards,
Saeed

**Comment by ericaweng** [comment]
Thank you for your response and the tips. I will do as you have suggested!
Good luck on the deadline.
