### ISSUE TITLE
Permutations on STGCNN and PECNet

### ISSUE THREAD

**Issue by HRHLALALA** [vita-epfl/s-attack#4]
Hi, great work! Can you provide the permutation trajectories obtained from PECNet and STGCNN publicly or privately if their code option cannot be released easily? I hope I can use them to do quick collision tests on other models. Thanks.

**Comment by SaeedSaadatnejad** [comment]
Hello,
Sorry for answering late. Unfortunately, we are not able to publish S-attack code on PECNet and STS-GCN nor their permuted trajectories. You should load their codes and models, freeze them and then use our attack function to find those perturbations.
