### ISSUE TITLE
Extension to argoverse2 dataset

### ISSUE THREAD

**Issue by Ahmed-Radwan094** [vita-epfl/s-attack#6]
Hi, thank you for the great work.
I want to extend scene attack methodology to ArgoVerse2 and was wondering if provide me with a starting point on what to change and where?
Best,
Ahmed

**Comment by MohammadHossein-Bahari** [comment]
Hello Ahmed,

Thanks for your interest in our work. 
Argoverse 2 API is different from Argoverse 1 (https://github.com/argoverse/av2-api/issues/46).
If you want to update current codebase to support Argoverse 2, you mainly need to change dataloaders to use Argoverse 2 API. 
There are different parts you need to change, and I think you can start by changing functions [here](https://github.com/vita-epfl/s-attack/blob/e053e24790ad88e1d3928d3cdafbd4d8fe7b7bf0/scene-attack/scenario_attacker.py#L114) and [here](https://github.com/vita-epfl/s-attack/blob/e053e24790ad88e1d3928d3cdafbd4d8fe7b7bf0/scene-attack/scenario_attacker.py#L115) to adapt to Argoverse 2. 

Another approach is to transfer s-attack to a new baseline. To this end, first, prepare a model running on Argoverse 2. You can check our [recent work](https://github.com/vita-epfl/UniTraj) for accessing multiple SOTA baselines on Argoverse 2.
Then, apply s-attack functions directly into the code. You can find the algorithm in Alg.1 in the supplementary material of the paper. Mainly, you need to transfer [apply_transform_function](https://github.com/vita-epfl/s-attack/blob/e053e24790ad88e1d3928d3cdafbd4d8fe7b7bf0/scene-attack/scenario_attacker.py#L525) and [correct_history](https://github.com/vita-epfl/s-attack/blob/e053e24790ad88e1d3928d3cdafbd4d8fe7b7bf0/scene-attack/scenario_attacker.py#L270).

Hope it helps.

**Comment by Ahmed-Radwan094** [comment]
Hi Mohammad,
Thanks for the information. I will work on the first option.
